/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hello.client.api;

import hello.client.model.Greeting;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GreetingControllerApi
 */
@Ignore
public class GreetingControllerApiTest {

    private final GreetingControllerApi api = new GreetingControllerApi();

    
    /**
     * greeting
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void greetingUsingGETTest() {
        String name = null;
        Greeting response = api.greetingUsingGET(name);

        // TODO: test validations
    }
    
}
